# fly.toml app configuration file generated for west-reservoir-watcher on 2026-05-26T16:39:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'west-reservoir-watcher'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 1
  max_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 256

[deploy]
  strategy = 'immediate'
